<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf6e40f911325082a7bd4739e38a117f6
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'App\\Models\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'App\\Models\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/Models',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf6e40f911325082a7bd4739e38a117f6::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf6e40f911325082a7bd4739e38a117f6::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitf6e40f911325082a7bd4739e38a117f6::$classMap;

        }, null, ClassLoader::class);
    }
}
